include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    public_member_api_docs: true
    avoid_print: true
    avoid_redundant_argument_values: true
    always_use_package_imports: true
    use_full_hex_values_for_flutter_colors: true

analyzer:
  exclude:
    - build/**
  errors:
    invalid_annotation_target: ignore
